# Generated by Django 4.2.1 on 2023-06-03 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_products_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Zanzibar', 'Zanzibar'), ('Dar-es-salaam', 'Dar-es-salaam'), ('Pemba', 'Pemba'), ('Dodoma', 'Dodoma'), ('Arusha', 'Arusha'), ('Bagamoyo', 'Bagamoyo'), ('Morogoro', 'Morogoro'), ('Singida', 'Singida'), ('Morogoro', 'Morogoro'), ('Iringa', 'Iringa'), ('Mtwara', 'Mtwara')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
